tf:
  connection:
    timeout: 30000
  sensor:
    temperature:
      max: 150.0
      tolerance: 2.0
      room: B5G
      object: B6L
  io:
    plug:
      smoker:
        id: rzt
        relay: 1
      oven:
        id: rzt
        relay: 2